FUNCTION main() AS INT
    PRINT "HELLO WORLD!"

    PRINT RED "HELLO WORLD!"
    PRINT ORANGE "HELLO WORLD!"
    PRINT YELLOW "HELLO WORLD!"
    PRINT GREEN "HELLO WORLD!"
    PRINT BLUE "HELLO WORLD!"
    PRINT INDIGO "HELLO WORLD!"
    PRINT VIOLET "HELLO WORLD!"
ENDFUNCTION